# Python-дағы ОББ, ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттер, NumPy кіріспе (массивтер, векторизация, негізгі операциялар)

1. Мақсат                                                                        
Python тілінде объектілі-бағытталған бағдарламалау (ОББ), ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттермен жұмыс, сондай-ақ NumPy кітапханасындағы негізгі операцияларды меңгеру.

# Есеп 1.1:

---
Кітап (Kitap) атты класс құрыңыз. Бұл кластың атауы (atau) және авторы (avtory) деген екі атрибуты болуы керек.\
__init__ әдісін қолданып, кітап атауын және авторын инициализациялаңыз.\
Класс ішінде кітап_туралы_мәлімет (kitap_turaly_malimet) атты әдіс жасаңыз. Бұл әдіс "Кітап: [Атауы], Авторы: [Авторы]" деген мәтінді консольға шығаруы керек.\
Осы класстан бір нысан (объект) жасаңыз және кітап_туралы_мәлімет әдісін шақырыңыз.

In [7]:
class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau
        self.avtory = avtory

    def kitap_turaly_malimet(self):

        print(f"Кітап: {self.atau}, Авторы: {self.avtory}")
menyn_kitabym = Kitap("Абай жолы", "Мұхтар Әуезов")
menyn_kitabym.kitap_turaly_malimet()

Кітап: Абай жолы, Авторы: Мұхтар Әуезов


# Есеп 2.1:

---

numpy кітапханасын np ретінде импорттаңыз.\
1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз.\
3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз. Мысалы, 1-ден 9-ға дейінгі сандарды пайдаланыңыз.\
Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз.

In [10]:
import numpy as np

# 1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз
arr_a = np.arange(1, 10)

# 3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз
arr_b = arr_a.reshape(3, 3)

# Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз
print("arr_a массиві:")
print(arr_a)
print(f"Өлшемі (shape): {arr_a.shape}")
print(f"Деректер түрі (dtype): {arr_a.dtype}")


arr_a массиві:
[1 2 3 4 5 6 7 8 9]
Өлшемі (shape): (9,)
Деректер түрі (dtype): int64


In [11]:
print("arr_b массиві:")
print(arr_b)
print(f"Өлшемі (shape): {arr_b.shape}")
print(f"Деректер түрі (dtype): {arr_b.dtype}")


arr_b массиві:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Өлшемі (shape): (3, 3)
Деректер түрі (dtype): int64


# Есеп 3.1:


---

numpy-ді np ретінде импорттаңыз.\
Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін (vec1 және vec2) жасаңыз (мысалы, 1-ден 10-ға дейінгі).\
Векторизацияны қолдана отырып (циклсіз):
- Екі массивті қосыңыз (vec1 + vec2).
- Әрбір элементтің квадратын есептеңіз (vec1 ** 2).
vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз.\

Барлық нәтижелерді консольға шығарыңыз.

In [12]:
import numpy as np

# Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін жасаңыз (1-ден 10-ға дейінгі)

vec1 = np.random.randint(1, 11, 5)
vec2 = np.random.randint(1, 11, 5)

print(f"vec1 массиві: {vec1}")
print(f"vec2 массиві: {vec2}")
print("-" * 30)

# Векторизацияны қолдана отырып (циклсіз):

# 1. Екі массивті қосыңыз (vec1 + vec2)
sum_result = vec1 + vec2
print(f"Қосындысы (vec1 + vec2): {sum_result}")

# 2. Әрбір элементтің квадратын есептеңіз (vec1 ** 2)
square_result = vec1 ** 2
print(f"vec1 элементтерінің квадраты: {square_result}")

# 3. vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз
mean_value = vec1.mean()
max_value = vec1.max()

print(f"vec1 орташа мәні (.mean()): {mean_value}")
print(f"vec1 ең үлкен мәні (.max()): {max_value}")

vec1 массиві: [ 5  3  6  5 10]
vec2 массиві: [2 5 3 4 4]
------------------------------
Қосындысы (vec1 + vec2): [ 7  8  9  9 14]
vec1 элементтерінің квадраты: [ 25   9  36  25 100]
vec1 орташа мәні (.mean()): 5.8
vec1 ең үлкен мәні (.max()): 10
